#! /bin/sh
#
# $Id: irchat-mkdist,v 1.9 1999/10/03 10:13:29 tri Exp $
#
# This file is part of irchat.  Command irchat-mkdist creates 
# a snapshot of irchat current.  This file itself does not go 
# into the snapshot archive.
#
# Author: Timo J. Rinne <tri@iki.fi>
#
# This file is covered by the copyright notice in irchat-copyright.el.
#

distfiles=""

clogdir="`finger -l jsl | sed -n 's,^.*[Dd]irectory: \([^ ]*/jsl\)*.*$,\1/irchat,p' 2>/dev/null | head -1`" 

if [ "x$1" != "x" ] ; then
    distname="irchat-""$1"
else
    distname="irchat-`date -u '+%y%m%d'`"
fi

[ -d "$distname" ] && { echo "You have already made $distname today."; exit 1; }

for i in RCS/*,v ; do
    if [ -f $i ] ; then
        file=`echo $i | sed 's+^RCS/\(.*\),v$+\1+'`
        if [ "$file" != "irchat-mkdist" ] ; then
            distfiles="$distfiles $file"
        fi
    fi
done

for i in $distfiles ; do
    co $i
    if [ $? -ne 0 ] ; then
        exit 1
    fi
done

co -l irchat-version.el &&
     ci -u -f -m"Irchat mkdist." irchat-version.el &&
     co irchat-version.el &&
     mkdir "$distname" &&
     cp $distfiles "$distname" &&
     ( if [ -f "$clogdir/ChangeLog" -a -r "$clogdir/ChangeLog" ]
       then
           cp "$clogdir/ChangeLog" "$distname"
       fi
       true ) &&
     ( cd "$distname" &&
       ttt="/tmp/xxx.$$"
       rm -f "$ttt"
       for i in ./*
       do
         cat "$i" | gawk 'BEGIN { s = 1; }
                         { if      (match($0, "^... BEGIN NODIST")) { s = 0 }
                           else if (match($0, "^... END NODIST"))   { s = 1 }
                           else if (s == 1) { print $0 } }' > "$ttt"
         rm -f "$i"
         cat "$ttt" > "$i"
         rm -f "$ttt"
       done
       true ) &&
     chmod 755 "$distname" &&
     (
          cd "$distname" &&
          gmake xemacs-compact &&
          mv irchat.elc irchat-xemacs-elc &&
          gmake gnuemacs-compact &&
          mv irchat.elc irchat-gnuemacs-elc &&
          mv irchat-xemacs-elc irchat-xemacs.elc &&
          mv irchat-gnuemacs-elc irchat-gnuemacs.elc
     )
     chmod a-w,a+r,u+w "$distname"/* &&
     tar cvf "$distname"".tar" ./"$distname" &&
     gzip -9 "$distname"".tar" &&
     ls -l "$distname"".tar.gz" &&
     rm -rf "$distname" &&
     exit 0

exit 2

# eof (irchat-mkdist)
